<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <!--
    <head>
        <meta charset="UTF-8">
            <title>prova Flavio</title>
            <link href="css/layout.css" rel="stylesheet" type="text/css" />
    </head>
    -->
    <?php include 'headers.php'; ?>
    <body>
        <div class="col-1">
            <ul class="list">
                <li><span><a href="<?php echo Utils::createLink('home'); ?>">Home</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('list', array('status' => ClientSocials::STATUS_PENDING)); ?>"
                             >Works Pending</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('list', array('status' => ClientSocials::STATUS_DONE)); ?>"
                             >Works Done</a></span></li>
                <li><span><a href="<?php echo Utils::createLink('list', array('status' => ClientSocials::STATUS_SENT)); ?>"
                             >Works Sent</a></span></li>
                <li class="last"><span><a href="<?php echo Utils::createLink('add-edit'); ?>"
                                          >Add new work</a></span></li>
            </ul>
        </div>
        <div class="col-2">
            <?php require $template; ?>
        </div>
    </body>
</html>
