<?php

?>
<h1>MANAGER SOCIALSTREAM'S DATA</h1>

<!--<p class="p">Welcome to the NetBeans PHP IDE sample - <b>TODO List application</b>.</p>-->
<ul class="list-1">
    Da questa maschera è possibile:
    <li>Visualizzare i lavori non ancora completati <b>Works Pending</b></li>
    <li>Visualizzare i lavori completati ma non inviati al cliente <b>Works Done</b></li>
    <li>Visualizzare i lavori inviati al cliente <b>Works Sent</b></li>
    <li>Inserire un nuovo lavoro <b>Add new work</b>
        <ul class="list-2">
            Nella maschera di inserimento si dovranno inserire obbligatoriamente:
            <li>Nome del cliente (comparirà nel centro in alto)</li>
            <li>Il nome di chi sta inserendo il dato</li>
            <li>I dati dei social</li>
            <p>I dati dei social, screen name e number id, non sono obbligatori ma
            a seconda del social che si vuole inserire nello stream sarà obbligatorio inserire
            screen name e/o number id</p>
        </ul>
    </li>
    All'interno degli elenchi dei lavori (pendenti, completati, inviati), scegliendo
    un cliente si vedrà la pagina con i dettagli presenti nel database, al piè di pagina
    si potrà
    <li>spostare il cliente da un elenco ad un altro</li>
    <li>modificare i dati precedentemente caricati</li>
    <li>cancellare il cliente e i suoi dati</li>
    <li>visualizzare lo stream del cliente</li>
</ul>